//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.01 at 07:46:12 AM PDT 
//


package com.bp.bs;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bp.bs package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bp.bs
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BooksState }
     * 
     */
    public BooksState createBooksState() {
        return new BooksState();
    }

    /**
     * Create an instance of {@link ReviewsState }
     * 
     */
    public ReviewsState createReviewsState() {
        return new ReviewsState();
    }

    /**
     * Create an instance of {@link ReviewRef }
     * 
     */
    public ReviewRef createReviewRef() {
        return new ReviewRef();
    }

    /**
     * Create an instance of {@link BookState }
     * 
     */
    public BookState createBookState() {
        return new BookState();
    }

    /**
     * Create an instance of {@link ReviewState }
     * 
     */
    public ReviewState createReviewState() {
        return new ReviewState();
    }

}
