//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.09.01 at 07:46:12 AM PDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://bp.com/bs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.bp.bs;
